<div class="import-export-part-sku-to-model">
    <?php if (!$block->getIsReadonly()): ?>
        <div class="import-part-sku-to-model">
            <?php if ($block->getUseContainer()): ?>
                <form id="import-form"
                      class="admin__fieldset"
                      action="<?= $block->escapeUrl($block->getUrl('purei_partskutomodel/importexport/importPost')) ?>"
                      method="post"
                      enctype="multipart/form-data">
                      <?php endif; ?>
                      <?= $block->getBlockHtml('formkey') ?>
                <div class="fieldset admin__field">
                    <label for="import_part_sku_to_model_file" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Import part_sku_to_model')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="file"
                               id="import_part_sku_to_model_file"
                               name="import_part_sku_to_model_file"
                               class="input-file required-entry"/>
                               <?= $block->getButtonHtml(__('Import part_sku_to_model'), '', 'import-submit') ?>
                    </div>
                </div>
                <?php if ($block->getUseContainer()): ?>
                </form>
            <?php endif; ?>
            <?php $scriptString = <<<script

    require(['jquery', 'Magento_Ui/js/modal/alert', "mage/mage", "loadingPopup", 'mage/translate'],
        function(jQuery, uiAlert){

    jQuery('#import-form').mage('form').mage('validation');
    (function ($) {
        $('.import-submit').click(function(){
            if($(':input[name="import_part_sku_to_model_file"]').val()) {
                $('body').loadingPopup({
                    timeout: false
                });

                $(this.form).submit();
            } else {
                uiAlert({
                    content: $.mage.__('Please select a file to import!')
                });
            }
        });
    })(jQuery);

});

script;
            ?>
            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
        </div>
    <?php endif; ?>
    <div class="export-part-sku-to-model <?= ($block->getIsReadonly()) ? 'box-left' : 'box-right' ?>">
        <?php if ($block->getUseContainer()): ?>
            <form id="export_form"
                  class="admin__fieldset"
                  action="<?= $block->escapeUrl($block->getUrl('purei_partskutomodel/importexport/exportPost')) ?>"
                  method="post"
                  enctype="multipart/form-data">
                  <?php endif; ?>
                  <?= $block->getBlockHtml('formkey') ?>
            <div class="fieldset admin__field">
                <span class="admin__field-label"><span><?= $block->escapeHtml(__('Export part_sku_to_model')) ?></span></span>
                <div class="admin__field-control">
                    <?= $block->getButtonHtml(__('Export part_sku_to_model'), "export_form.submit()") ?>
                </div>
            </div>
            <?php if ($block->getUseContainer()): ?>
            </form>
        <?php endif; ?>
    </div>
</div>
