<div class="import-export-part-sku-to-model">
    <div class="import-part-sku-to-model">
        <form id="import-form"
              action="<?= $block->escapeUrl($block->getUrl('purei_partskutomodel/importexport/importPost')) ?>"
              method="post"
              enctype="multipart/form-data">
                  <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset admin__fieldset">
                <legend class="admin__legend legend">
                    <span>Import</span>
                </legend><br>
                <div class="admin__field field field-theme_id  required _required">
                    <label class="label admin__field-label" for="import_part_sku_to_model_delimiter">
                        <span>
                            Delimiter
                        </span>
                    </label>
                    <div class="admin__field-control control">
                        <select id="import_part_sku_to_model_delimiter" name="import_part_sku_to_model_delimiter"
                                class="required-entry _required select admin__control-select">
                            <option value="comma">comma delimited</option>
                            <option value="tab">tab separated</option>
                        </select>
                    </div>
                </div>
                <div class="admin__field field field-import_part_sku_to_model_file  required _required">
                    <label class="label admin__field-label" for="import_part_sku_to_model_file">
                        <span>CSV File</span>
                    </label>
                    <div class="admin__field-control control">
                        <input id="import_part_sku_to_model_file"
                               name="import_part_sku_to_model_file"
                               title="CSV File" type="file"
                               class="required-entry _required">               
                    </div>
                </div>
                <div class="admin__field field field-import  with-addon no-label">
                    <div class="admin__field-control control">
                        <div class="admin__field">
                            <?= $block->getButtonHtml(__('Submit'), '', 'import-submit') ?>
                        </div>                  
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <hr />
    <div class="export-part-sku-to-model <?= ($block->getIsReadonly()) ? 'box-left' : 'box-right' ?>">
        <form id="export_form"
              class="admin__fieldset"
              action="<?= $block->escapeUrl($block->getUrl('purei_partskutomodel/importexport/exportPost')) ?>"
              method="post">
                  <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset admin__fieldset">
                <legend class="admin__legend legend">
                    <span>Export</span>
                </legend><br>
                <div class="fieldset admin__field">
                    <div class="admin__field-control">
                        <?= $block->getButtonHtml(__('Submit'), '', 'export-submit') ?>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<?php $scriptString = <<<script

    require(['jquery', 'Magento_Ui/js/modal/alert', "mage/mage", "loadingPopup", 'mage/translate'],
        function(jQuery, uiAlert){
    jQuery('#import-form').mage('form').mage('validation');
    (function ($) {
        
        $('.export-submit').click(function(){
            $('body').loadingPopup({
                timeout: 1000
            });
            $(this.form).submit();
        });
        
        $('.import-submit').click(function(){
            if($(':input[name="import_part_sku_to_model_file"]').val()) {
                $('body').loadingPopup({
                    timeout: false
                });
                $(this.form).submit();
            } else {
                uiAlert({
                    content: $.mage.__('Please select a file to import!')
                });
            }
        });
    })(jQuery);
});
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>